export const OPD_MODULE_KEYS = [
  'LAYANAN_KEPEGAWAIAN',
  'SIPENSIUN',
  'SIDATA',
  'DMS',
] as const;

export type OpdModuleKey = (typeof OPD_MODULE_KEYS)[number];

export const PPIK_PEREMAJAAN_SERVICE_TYPES = [
  'PEREMAJAAN_NIK',
  'PEREMAJAAN_NAMA',
  'PEREMAJAAN_TANGGAL_LAHIR',
  'PEREMAJAAN_KELUARGA_TAMBAH_ANAK',
  'PEREMAJAAN_KELUARGA_MENIKAH',
  'PEREMAJAAN_KELUARGA_CERAI',
  'PEREMAJAAN_KONTAK_ALAMAT_EMAIL',
  'PEREMAJAAN_GOLONGAN',
  'PEREMAJAAN_PENDIDIKAN',
] as const;

export const PPIK_PEMBERHENTIAN_SERVICE_TYPES = [
  'PEMBERHENTIAN_BUP',
  'PEMBERHENTIAN_APS',
  'PEMBERHENTIAN_MENINGGAL',
  'PEMBERHENTIAN_TIDAK_CAKAP',
  'PEMBERHENTIAN_PIDANA_DISIPLIN',
  'PEMBERHENTIAN_HILANG_TEWAS',
  'PENSIUN_JANDA_DUDA_AHLI_WARIS',
] as const;

export const LAYANAN_SERVICE_TYPES = [
  ...PPIK_PEREMAJAAN_SERVICE_TYPES,
  ...PPIK_PEMBERHENTIAN_SERVICE_TYPES,
] as const;

export type PpikPeremajaanServiceType =
  (typeof PPIK_PEREMAJAAN_SERVICE_TYPES)[number];

export type PpikPemberhentianServiceType =
  (typeof PPIK_PEMBERHENTIAN_SERVICE_TYPES)[number];

export type LayananServiceType = (typeof LAYANAN_SERVICE_TYPES)[number];

export const PPIK_REQUIRED_DOCUMENT_TYPES: Record<LayananServiceType, string[]> = {
  PEREMAJAAN_NIK: ['KTP'],
  PEREMAJAAN_NAMA: ['AKTA_LAHIR'],
  PEREMAJAAN_TANGGAL_LAHIR: ['AKTA_LAHIR'],

  PEREMAJAAN_KELUARGA_TAMBAH_ANAK: ['AKTA_KELAHIRAN_ANAK', 'KARTU_KELUARGA'],
  PEREMAJAAN_KELUARGA_MENIKAH: ['BUKU_NIKAH_ATAU_AKTA_NIKAH', 'KARTU_KELUARGA'],
  PEREMAJAAN_KELUARGA_CERAI: ['AKTA_CERAI_ATAU_PUTUSAN_PENGADILAN', 'KARTU_KELUARGA'],

  PEREMAJAAN_KONTAK_ALAMAT_EMAIL: ['FORMULIR_PERUBAHAN_DATA'],
  PEREMAJAAN_GOLONGAN: ['SK_PANGKAT_ATAU_SK_GOLONGAN'],
  PEREMAJAAN_PENDIDIKAN: ['IJAZAH', 'TRANSKRIP_NILAI'],

  PEMBERHENTIAN_BUP: ['USULAN_OPD', 'DATA_ASN', 'SK_PANGKAT_TERAKHIR'],
  PEMBERHENTIAN_APS: ['SURAT_PERMOHONAN', 'REKOMENDASI_OPD', 'DOKUMEN_KEPEGAWAIAN'],
  PEMBERHENTIAN_MENINGGAL: ['AKTA_KEMATIAN_ATAU_SURAT_KETERANGAN_KEMATIAN', 'DOKUMEN_AHLI_WARIS'],
  PEMBERHENTIAN_TIDAK_CAKAP: ['SURAT_KETERANGAN_MEDIS_ATAU_PENETAPAN_RESMI', 'REKOMENDASI_OPD'],
  PEMBERHENTIAN_PIDANA_DISIPLIN: ['PUTUSAN_PENGADILAN_ATAU_KEPUTUSAN_DISIPLIN', 'TELAAHAN'],
  PEMBERHENTIAN_HILANG_TEWAS: ['DOKUMEN_PENETAPAN_ATAU_KETERANGAN_RESMI'],
  PENSIUN_JANDA_DUDA_AHLI_WARIS: ['DOKUMEN_AHLI_WARIS', 'DOKUMEN_KEPEGAWAIAN', 'DOKUMEN_PENDUKUNG_PENSIUN'],
};

export function isPpikPeremajaanServiceType(
  value: string | undefined | null,
): value is PpikPeremajaanServiceType {
  return PPIK_PEREMAJAAN_SERVICE_TYPES.includes(
    value as PpikPeremajaanServiceType,
  );
}

export function isPpikPemberhentianServiceType(
  value: string | undefined | null,
): value is PpikPemberhentianServiceType {
  return PPIK_PEMBERHENTIAN_SERVICE_TYPES.includes(
    value as PpikPemberhentianServiceType,
  );
}

export function isLayananServiceType(
  value: string | undefined | null,
): value is LayananServiceType {
  return LAYANAN_SERVICE_TYPES.includes(value as LayananServiceType);
}

export function getRequiredDocumentTypes(serviceType: LayananServiceType): string[] {
  return PPIK_REQUIRED_DOCUMENT_TYPES[serviceType];
}