export const KINERJA_BIDANG_READ_ROLES = [
  'SUPER_ADMIN',
  'ADMIN_BKPSDM',
  'KEPALA_BADAN',
  'KABID',
  'ANALIS_MADYA',
  'ANALIS_MUDA',
  'ANALIS_PERTAMA',
  'PENELAAH',
  'PPPK',
] as const;

export const KINERJA_BIDANG_WRITE_ROLES = [
  'SUPER_ADMIN',
  'ADMIN_BKPSDM',
  'KABID',
  'ANALIS_MADYA',
  'ANALIS_MUDA',
  'ANALIS_PERTAMA',
  'PENELAAH',
  'PPPK',
] as const;

export const KINERJA_BIDANG_REVIEW_ROLES = [
  'SUPER_ADMIN',
  'ADMIN_BKPSDM',
  'KEPALA_BADAN',
  'KABID',
] as const;

export const KINERJA_BIDANG_SEED_ROLES = ['SUPER_ADMIN', 'ADMIN_BKPSDM', 'KABID'] as const;
