import { SopStage, SopTargetUnit } from '@prisma/client';

export interface KinerjaBidangSeedSop {
  code: string;
  title: string;
  stage: SopStage;
  stageTitle: string;
  shortDescription: string;
  rhkCodes: string[];
  targetQuantity: number;
  targetUnit: SopTargetUnit;
  qualityTarget: string;
  timeTarget: string;
  isRhkPrimary: boolean;
  sortOrder: number;
}

export const KINERJA_BIDANG_SEED_SOP: KinerjaBidangSeedSop[] = [
  {
    code: 'SOP-BKPSDM-MAN-001',
    title: 'Perencanaan Program dan Kegiatan Bidang',
    stage: SopStage.TAHAP_1,
    stageTitle: 'SOP Manajemen Bidang',
    shortDescription:
      'Mengatur penyusunan rencana program, kegiatan, target, jadwal, kebutuhan data, dan prioritas kerja Bidang PPIK.',
    rhkCodes: ['SEMUA_RHK'],
    targetQuantity: 1,
    targetUnit: SopTargetUnit.DOKUMEN,
    qualityTarget: '90%-100%',
    timeTarget: 'Tahunan / awal tahun anggaran',
    isRhkPrimary: false,
    sortOrder: 10,
  },
  {
    code: 'SOP-BKPSDM-MAN-002',
    title: 'Pembagian Tugas Internal Bidang',
    stage: SopStage.TAHAP_1,
    stageTitle: 'SOP Manajemen Bidang',
    shortDescription: 'Mengatur pembagian tugas internal Bidang PPIK.',
    rhkCodes: ['SEMUA_RHK'],
    targetQuantity: 1,
    targetUnit: SopTargetUnit.DOKUMEN,
    qualityTarget: '90%-100%',
    timeTarget: 'Tahunan / sesuai kebutuhan',
    isRhkPrimary: false,
    sortOrder: 20,
  },
  {
    code: 'SOP-BKPSDM-MAN-003',
    title: 'Monitoring Pelaksanaan Kegiatan Bidang',
    stage: SopStage.TAHAP_1,
    stageTitle: 'SOP Manajemen Bidang',
    shortDescription:
      'Mengatur pemantauan progres kegiatan, hambatan, risiko keterlambatan, tindak lanjut, dan capaian output bidang.',
    rhkCodes: ['SEMUA_RHK'],
    targetQuantity: 12,
    targetUnit: SopTargetUnit.LAPORAN,
    qualityTarget: '90%-100%',
    timeTarget: 'Bulanan',
    isRhkPrimary: false,
    sortOrder: 30,
  },
  {
    code: 'SOP-BKPSDM-MAN-004',
    title: 'Pelaporan Kinerja Bidang',
    stage: SopStage.TAHAP_1,
    stageTitle: 'SOP Manajemen Bidang',
    shortDescription: 'Mengatur penyusunan laporan kinerja bidang berdasarkan capaian RHK dan bukti dukung.',
    rhkCodes: ['RHK 2'],
    targetQuantity: 1,
    targetUnit: SopTargetUnit.DOKUMEN,
    qualityTarget: '90%-100%',
    timeTarget: 'Tahunan / periodik',
    isRhkPrimary: false,
    sortOrder: 40,
  },
  {
    code: 'SOP-BKPSDM-MAN-005',
    title: 'Pengelolaan Dokumen dan Arsip Bidang',
    stage: SopStage.TAHAP_1,
    stageTitle: 'SOP Manajemen Bidang',
    shortDescription: 'Mengatur pengelolaan dokumen kerja, arsip bidang, dan bukti dukung kegiatan.',
    rhkCodes: ['RHK 7'],
    targetQuantity: 12,
    targetUnit: SopTargetUnit.LAPORAN,
    qualityTarget: '90%-100%',
    timeTarget: 'Bulanan',
    isRhkPrimary: false,
    sortOrder: 50,
  },
  {
    code: 'SOP-BKPSDM-LAY-001',
    title: 'Penerimaan Permohonan Layanan Kepegawaian',
    stage: SopStage.TAHAP_2,
    stageTitle: 'SOP Pengelolaan Layanan Kepegawaian',
    shortDescription: 'Mengatur penerimaan permohonan layanan kepegawaian dari OPD/ASN.',
    rhkCodes: ['RHK 1', 'RHK 3', 'RHK 4', 'RHK 8'],
    targetQuantity: 12,
    targetUnit: SopTargetUnit.LAPORAN,
    qualityTarget: '90%-100%',
    timeTarget: 'Bulanan / sesuai layanan',
    isRhkPrimary: false,
    sortOrder: 110,
  },
  {
    code: 'SOP-BKPSDM-LAY-002',
    title: 'Verifikasi Kelengkapan Berkas Layanan',
    stage: SopStage.TAHAP_2,
    stageTitle: 'SOP Pengelolaan Layanan Kepegawaian',
    shortDescription: 'Mengatur pemeriksaan kelengkapan dan kesesuaian berkas layanan.',
    rhkCodes: ['RHK 1', 'RHK 3'],
    targetQuantity: 12,
    targetUnit: SopTargetUnit.LAPORAN,
    qualityTarget: '90%-100%',
    timeTarget: 'Bulanan / sesuai SLA',
    isRhkPrimary: false,
    sortOrder: 120,
  },
  {
    code: 'SOP-BKPSDM-LAY-003',
    title: 'Monitoring SLA Layanan Kepegawaian',
    stage: SopStage.TAHAP_2,
    stageTitle: 'SOP Pengelolaan Layanan Kepegawaian',
    shortDescription: 'Mengatur pemantauan ketepatan waktu layanan dan pelaporan SLA.',
    rhkCodes: ['RHK 8'],
    targetQuantity: 12,
    targetUnit: SopTargetUnit.LAPORAN,
    qualityTarget: '90%-100%',
    timeTarget: 'Bulanan',
    isRhkPrimary: false,
    sortOrder: 130,
  },
  {
    code: 'SOP-BKPSDM-LAY-004',
    title: 'Penanganan Keterlambatan Layanan',
    stage: SopStage.TAHAP_2,
    stageTitle: 'SOP Pengelolaan Layanan Kepegawaian',
    shortDescription: 'Mengatur tindak lanjut atas layanan yang melewati batas waktu.',
    rhkCodes: ['RHK 8'],
    targetQuantity: 12,
    targetUnit: SopTargetUnit.LAPORAN,
    qualityTarget: '90%-100%',
    timeTarget: 'Bulanan / insidental',
    isRhkPrimary: false,
    sortOrder: 140,
  },
  {
    code: 'SOP-BKPSDM-LAY-005',
    title: 'Evaluasi Kepuasan Layanan',
    stage: SopStage.TAHAP_2,
    stageTitle: 'SOP Pengelolaan Layanan Kepegawaian',
    shortDescription: 'Mengatur evaluasi kepuasan pengguna layanan dan rekomendasi perbaikan.',
    rhkCodes: ['RHK 8'],
    targetQuantity: 2,
    targetUnit: SopTargetUnit.LAPORAN,
    qualityTarget: '90%-100%',
    timeTarget: 'Semesteran',
    isRhkPrimary: false,
    sortOrder: 150,
  },
  {
    code: 'SOP-BKPSDM-FNG-001',
    title: 'Penyusunan Rencana Kebutuhan ASN',
    stage: SopStage.TAHAP_3,
    stageTitle: 'SOP Fungsi Spesifik Bidang',
    shortDescription: 'Mengatur penyusunan kebutuhan ASN berdasarkan data pegawai dan kebutuhan organisasi.',
    rhkCodes: ['RHK 1'],
    targetQuantity: 1,
    targetUnit: SopTargetUnit.DOKUMEN,
    qualityTarget: '90%-100%',
    timeTarget: 'Tahunan / sesuai jadwal nasional',
    isRhkPrimary: false,
    sortOrder: 210,
  },
  {
    code: 'SOP-BKPSDM-FNG-002',
    title: 'Verifikasi Usulan Formasi ASN',
    stage: SopStage.TAHAP_3,
    stageTitle: 'SOP Fungsi Spesifik Bidang',
    shortDescription: 'Mengatur verifikasi usulan formasi ASN dari perangkat daerah.',
    rhkCodes: ['RHK 1'],
    targetQuantity: 1,
    targetUnit: SopTargetUnit.DOKUMEN,
    qualityTarget: '90%-100%',
    timeTarget: 'Tahunan / sesuai jadwal nasional',
    isRhkPrimary: false,
    sortOrder: 220,
  },
  {
    code: 'SOP-BKPSDM-PAN-001',
    title: 'Pengendalian Pelaksanaan Pengadaan ASN',
    stage: SopStage.TAHAP_3,
    stageTitle: 'SOP Fungsi Spesifik Bidang',
    shortDescription: 'Mengatur pengendalian pelaksanaan pengadaan ASN sampai pelaporan.',
    rhkCodes: ['RHK 1'],
    targetQuantity: 5,
    targetUnit: SopTargetUnit.LAPORAN,
    qualityTarget: '90%-100%',
    timeTarget: 'Tahunan / sesuai tahapan pengadaan',
    isRhkPrimary: true,
    sortOrder: 230,
  },
  {
    code: 'SOP-BKPSDM-EVK-001',
    title: 'Evaluasi Kinerja Bidang',
    stage: SopStage.TAHAP_1,
    stageTitle: 'SOP Manajemen Bidang',
    shortDescription: 'Mengatur evaluasi capaian kinerja bidang berdasarkan RHK, realisasi, kendala, dan bukti dukung.',
    rhkCodes: ['RHK 2'],
    targetQuantity: 1,
    targetUnit: SopTargetUnit.DOKUMEN,
    qualityTarget: '90%-100%',
    timeTarget: 'Tahunan',
    isRhkPrimary: true,
    sortOrder: 240,
  },
  {
    code: 'SOP-BKPSDM-PBH-001',
    title: 'Pengendalian Pemberhentian ASN',
    stage: SopStage.TAHAP_3,
    stageTitle: 'SOP Fungsi Spesifik Bidang',
    shortDescription: 'Mengatur pengendalian proses pemberhentian ASN dan pensiun.',
    rhkCodes: ['RHK 3'],
    targetQuantity: 12,
    targetUnit: SopTargetUnit.LAPORAN,
    qualityTarget: '90%-100%',
    timeTarget: 'Bulanan',
    isRhkPrimary: true,
    sortOrder: 250,
  },
  {
    code: 'SOP-BKPSDM-LPA-001',
    title: 'Fasilitasi Lembaga Profesi ASN',
    stage: SopStage.TAHAP_3,
    stageTitle: 'SOP Fungsi Spesifik Bidang',
    shortDescription: 'Mengatur fasilitasi kelembagaan profesi ASN, koordinasi, pembinaan, dan pelaporan.',
    rhkCodes: ['RHK 4'],
    targetQuantity: 3,
    targetUnit: SopTargetUnit.LAPORAN,
    qualityTarget: '90%-100%',
    timeTarget: 'Triwulan / sesuai kebutuhan',
    isRhkPrimary: true,
    sortOrder: 260,
  },
  {
    code: 'SOP-BKPSDM-SIK-001',
    title: 'Pengelolaan Sistem Informasi Kepegawaian',
    stage: SopStage.TAHAP_3,
    stageTitle: 'SOP Fungsi Spesifik Bidang',
    shortDescription: 'Mengatur pengelolaan sistem informasi kepegawaian dan monitoring operasional sistem.',
    rhkCodes: ['RHK 5'],
    targetQuantity: 12,
    targetUnit: SopTargetUnit.LAPORAN,
    qualityTarget: '90%-100%',
    timeTarget: 'Bulanan',
    isRhkPrimary: true,
    sortOrder: 270,
  },
  {
    code: 'SOP-BKPSDM-DAT-001',
    title: 'Pengendalian Pengelolaan Data ASN',
    stage: SopStage.TAHAP_3,
    stageTitle: 'SOP Fungsi Spesifik Bidang',
    shortDescription: 'Mengatur pengendalian data ASN agar lengkap, mutakhir, konsisten, dan tervalidasi.',
    rhkCodes: ['RHK 6'],
    targetQuantity: 12,
    targetUnit: SopTargetUnit.LAPORAN,
    qualityTarget: '90%-100%',
    timeTarget: 'Bulanan',
    isRhkPrimary: true,
    sortOrder: 280,
  },
  {
    code: 'SOP-BKPSDM-DMS-001',
    title: 'Pengelolaan DMS & Data Kepegawaian',
    stage: SopStage.TAHAP_3,
    stageTitle: 'SOP Fungsi Spesifik Bidang',
    shortDescription:
      'Mengatur program pengelolaan dokumen dan data kepegawaian ASN sesuai kebutuhan program nasional BKN.',
    rhkCodes: ['RHK 7'],
    targetQuantity: 12,
    targetUnit: SopTargetUnit.LAPORAN,
    qualityTarget: '90%-100%',
    timeTarget: 'Bulanan',
    isRhkPrimary: true,
    sortOrder: 290,
  },
  {
    code: 'SOP-BKPSDM-LIK-001',
    title: 'Monev Publikasi Layanan Informasi Kepegawaian',
    stage: SopStage.TAHAP_3,
    stageTitle: 'SOP Fungsi Spesifik Bidang',
    shortDescription: 'Mengatur monitoring dan evaluasi publikasi layanan informasi kepegawaian.',
    rhkCodes: ['RHK 8'],
    targetQuantity: 2,
    targetUnit: SopTargetUnit.LAPORAN,
    qualityTarget: '90%-100%',
    timeTarget: 'Semesteran',
    isRhkPrimary: true,
    sortOrder: 300,
  },
];
