import {
  Archive,
  BarChart3,
  BookOpenCheck,
  CalendarDays,
  ClipboardCheck,
  Database,
  FileText,
  FolderArchive,
  Gauge,
  GitCompareArrows,
  GitBranch,
  Settings,
  ShieldAlert,
  ShieldCheck,
  ThumbsUp,
  Users,
} from 'lucide-react';
import { MenuConfig } from '@/config/types';
import {
  ADMIN_ROLES,
  EXECUTIVE_ROLES,
} from '@/lib/rbac/policies';

export const MENU_SIDEBAR: MenuConfig = [
  { heading: 'Workspace' },
  {
    title: 'Dashboard',
    icon: Gauge,
    path: '/dashboard',
    moduleKey: 'DASHBOARD',
  },
  {
    title: 'Inti SIAP',
    icon: GitBranch,
    moduleKey: 'SIAP',
    children: [
      {
        title: 'Dashboard Pimpinan',
        path: '/siap/worklogs/executive',
        icon: ShieldAlert,
        moduleKey: 'SIAP',
        requiredPermission: 'monitor',
        allowedRoles: EXECUTIVE_ROLES,
      },
      {
        title: 'Dashboard Buku Kerja',
        path: '/siap/worklogs/dashboard',
        icon: BarChart3,
        moduleKey: 'SIAP',
        requiredPermission: 'monitor',
      },
      {
        title: 'Tugas SIAP',
        path: '/siap/tasks',
        moduleKey: 'SIAP',
      },
      {
        title: 'Buku Kerja Saya',
        path: '/siap/worklogs',
        icon: BookOpenCheck,
        moduleKey: 'SIAP',
      },
      {
        title: 'Tinjau Buku Kerja',
        path: '/siap/worklogs/team',
        icon: ClipboardCheck,
        moduleKey: 'SIAP',
        requiredPermission: 'review',
      },
      {
        title: 'Disposisi & Arahan',
        path: '/siap/tasks?type=DISPOSISI',
        moduleKey: 'SIAP',
      },
      {
        title: 'Tindak Lanjut',
        path: '/siap/tasks?status=FOLLOW_UP',
        moduleKey: 'SIAP',
        requiredPermission: 'input',
      },
    ],
  },
  {
    title: 'Kinerja Bidang',
    icon: BarChart3,
    moduleKey: 'KINERJA_BIDANG',
    children: [
      {
        title: 'Dashboard Kinerja',
        path: '/kinerja-bidang',
        moduleKey: 'KINERJA_BIDANG',
      },
      {
        title: 'Rencana Kerja Bidang',
        path: '/kinerja-bidang/sop?stage=TAHAP_1',
        moduleKey: 'KINERJA_BIDANG',
      },
      {
        title: 'Target RHK',
        path: '/kinerja-bidang/targets',
        moduleKey: 'KINERJA_BIDANG',
        requiredPermission: 'monitor',
      },
      {
        title: 'Realisasi Bulanan',
        path: '/kinerja-bidang/realizations',
        moduleKey: 'KINERJA_BIDANG',
        requiredPermission: 'input',
      },
      {
        title: 'Monitoring Kegiatan',
        path: '/kinerja-bidang/realizations?status=SUBMITTED',
        moduleKey: 'KINERJA_BIDANG',
        requiredPermission: 'monitor',
      },
      {
        title: 'Laporan Kinerja',
        path: '/kinerja-bidang/report',
        moduleKey: 'KINERJA_BIDANG',
        requiredPermission: 'report',
      },
      {
        title: 'Bukti Dukung RHK',
        path: '/dms/documents?category=BUKTI_DUKUNG',
        moduleKey: 'DMS',
      },
    ],
  },
  {
    title: 'Layanan Kepegawaian',
    icon: ClipboardCheck,
    moduleKey: 'LAYANAN_KEPEGAWAIAN',
    children: [
      {
        title: 'Permohonan Masuk',
        path: '/layanan',
        moduleKey: 'LAYANAN_KEPEGAWAIAN',
      },
      {
        title: 'Meja Kerja Verifikasi',
        path: '/layanan/workbench',
        moduleKey: 'LAYANAN_KEPEGAWAIAN',
        requiredPermission: 'verify',
      },
      {
        title: 'Verifikasi Berkas',
        path: '/layanan/verifikasi',
        moduleKey: 'LAYANAN_KEPEGAWAIAN',
        requiredPermission: 'verify',
      },
      {
        title: 'Monitoring SLA',
        path: '/layanan/sla',
        moduleKey: 'LAYANAN_KEPEGAWAIAN',
        requiredPermission: 'monitor',
      },
      {
        title: 'Keterlambatan Layanan',
        path: '/layanan/keterlambatan',
        moduleKey: 'LAYANAN_KEPEGAWAIAN',
        requiredPermission: 'monitor',
      },
      {
        title: 'Evaluasi Kepuasan',
        path: '/layanan/kepuasan',
        moduleKey: 'LAYANAN_KEPEGAWAIAN',
        requiredPermission: 'monitor',
      },
      {
        title: 'Rekap Layanan',
        path: '/layanan/laporan',
        moduleKey: 'LAYANAN_KEPEGAWAIAN',
        requiredPermission: 'report',
      },
    ],
  },
  {
    title: 'IKM Survei Kepuasan',
    icon: ThumbsUp,
    moduleKey: 'LAYANAN_KEPEGAWAIAN',
    children: [
      {
        title: 'Hasil & Rekap IKM',
        path: '/layanan/kepuasan',
        moduleKey: 'LAYANAN_KEPEGAWAIAN',
        requiredPermission: 'monitor',
      },
      {
        title: 'Manajemen Periode IKM',
        path: '/layanan/ikm/periode',
        moduleKey: 'LAYANAN_KEPEGAWAIAN',
        requiredPermission: 'verify',
      },
      {
        title: 'Data Survei Masuk',
        path: '/layanan/ikm/data',
        moduleKey: 'LAYANAN_KEPEGAWAIAN',
        requiredPermission: 'monitor',
      },
    ],
  },
  {
    title: 'SIDATA ASN',
    icon: Database,
    moduleKey: 'SIDATA',
    children: [
      { title: 'Dashboard', path: '/sidata/dashboard', moduleKey: 'SIDATA' },
      { title: 'Profil ASN', path: '/sidata/asn', moduleKey: 'SIDATA' },
      {
        title: 'Validasi Data',
        path: '/sidata/validasi',
        moduleKey: 'SIDATA',
        requiredPermission: 'verify',
      },
      {
        title: 'Pemutakhiran Data',
        path: '/sidata/pemutakhiran',
        moduleKey: 'SIDATA',
        requiredPermission: 'input',
      },
      {
        title: 'Import & Sinkronisasi',
        moduleKey: 'SIDATA',
        requiredPermission: 'upload',
        children: [
          {
            title: 'Import SIASN',
            path: '/sidata/import/siasn',
            moduleKey: 'SIDATA',
            requiredPermission: 'upload',
          },
          {
            title: 'Import Excel',
            path: '/sidata/import/excel',
            moduleKey: 'SIDATA',
            requiredPermission: 'upload',
          },
          {
            title: 'Import Referensi',
            path: '/sidata/import/referensi',
            moduleKey: 'SIDATA',
            requiredPermission: 'upload',
          },
          {
            title: 'Mapping Referensi',
            path: '/sidata/import/mapping-referensi',
            moduleKey: 'SIDATA',
            requiredPermission: 'verify',
          },
          {
            title: 'Riwayat Import',
            path: '/sidata/import/riwayat',
            moduleKey: 'SIDATA',
            requiredPermission: 'monitor',
          },
          {
            title: 'Log Sinkronisasi',
            path: '/sidata/import/log-sinkronisasi',
            moduleKey: 'SIDATA',
            requiredPermission: 'monitor',
          },
        ],
      },
      {
        title: 'Rekonsiliasi Data',
        path: '/sidata/rekonsiliasi',
        moduleKey: 'SIDATA',
        requiredPermission: 'verify',
      },
      {
        title: 'Discrepancy Data',
        path: '/sidata/validasi?view=discrepancy',
        moduleKey: 'SIDATA',
        requiredPermission: 'verify',
      },
      { title: 'Referensi Data', path: '/sidata/referensi', moduleKey: 'SIDATA' },
      { title: 'Dokumen ASN', path: '/sidata/dokumen', moduleKey: 'SIDATA' },
      {
        title: 'Laporan',
        path: '/sidata/laporan',
        moduleKey: 'SIDATA',
        requiredPermission: 'report',
      },
    ],
  },
  {
    title: 'Rekonsiliasi BPKAD',
    icon: GitCompareArrows,
    moduleKey: 'REKONSILIASI_BPKAD',
    children: [
      {
        title: 'Dashboard',
        path: '/rekonsiliasi-bpkad/dashboard',
        moduleKey: 'REKONSILIASI_BPKAD',
      },
      {
        title: 'Manajemen Periode',
        path: '/rekonsiliasi-bpkad/periode',
        moduleKey: 'REKONSILIASI_BPKAD',
        requiredPermission: 'verify',
      },
      {
        title: 'Import Simgaji',
        path: '/rekonsiliasi-bpkad/import/simgaji',
        moduleKey: 'REKONSILIASI_BPKAD',
        requiredPermission: 'upload',
      },
      {
        title: 'Pencocokan Data',
        path: '/rekonsiliasi-bpkad/matching',
        moduleKey: 'REKONSILIASI_BPKAD',
        requiredPermission: 'verify',
      },
      {
        title: 'Matriks Temuan',
        path: '/rekonsiliasi-bpkad/temuan',
        moduleKey: 'REKONSILIASI_BPKAD',
        requiredPermission: 'verify',
      },
      {
        title: 'Tindak Lanjut',
        path: '/rekonsiliasi-bpkad/tindak-lanjut',
        moduleKey: 'REKONSILIASI_BPKAD',
        requiredPermission: 'input',
      },
      {
        title: 'Berita Acara',
        path: '/rekonsiliasi-bpkad/berita-acara',
        moduleKey: 'REKONSILIASI_BPKAD',
        requiredPermission: 'approve',
      },
      {
        title: 'Laporan',
        path: '/rekonsiliasi-bpkad/laporan',
        moduleKey: 'REKONSILIASI_BPKAD',
        requiredPermission: 'report',
      },
    ],
  },
  {
    title: 'DMS Bukti Dukung',
    icon: FolderArchive,
    moduleKey: 'DMS',
    children: [
      { title: 'Dashboard DMS', path: '/dms', moduleKey: 'DMS' },
      {
        title: 'Dokumen SOP',
        path: '/dms/documents?category=DOKUMEN_KEBIJAKAN',
        moduleKey: 'DMS',
      },
      {
        title: 'Bukti Dukung RHK',
        path: '/dms/documents?category=BUKTI_DUKUNG',
        moduleKey: 'DMS',
      },
      {
        title: 'Dokumen Layanan',
        path: '/dms/documents?category=ARSIP_KEPEGAWAIAN',
        moduleKey: 'DMS',
      },
      {
        title: 'Dokumen Keputusan',
        path: '/dms/documents?category=SURAT_DINAS',
        moduleKey: 'DMS',
      },
      {
        title: 'Upload Dokumen',
        path: '/dms/upload',
        moduleKey: 'DMS',
        requiredPermission: 'upload',
      },
      {
        title: 'Verifikasi Dokumen',
        path: '/dms/verification',
        moduleKey: 'DMS',
        requiredPermission: 'verify',
      },
      {
        title: 'Laporan DMS',
        path: '/dms/reports',
        moduleKey: 'DMS',
        requiredPermission: 'report',
      },
    ],
  },
  {
    title: 'SIPENSIUN',
    icon: FileText,
    moduleKey: 'SIPENSIUN',
    children: [
      {
        title: 'Dashboard',
        path: '/sipensiun?view=dashboard',
        moduleKey: 'SIPENSIUN',
        requiredPermission: 'monitor',
      },
      {
        title: 'Usulan Pensiun',
        moduleKey: 'SIPENSIUN',
        children: [
          {
            title: 'Penerimaan Usulan',
            path: '/sipensiun?view=received',
            moduleKey: 'SIPENSIUN',
            requiredPermission: 'input',
          },
          {
            title: 'Verifikasi Berkas',
            path: '/sipensiun?view=verification',
            moduleKey: 'SIPENSIUN',
            requiredPermission: 'verify',
          },
          { title: 'BUP', path: '/sipensiun?jenis=BUP', moduleKey: 'SIPENSIUN' },
          {
            title: 'Ahli Waris',
            path: '/sipensiun?jenis=AHLI_WARIS',
            moduleKey: 'SIPENSIUN',
          },
        ],
      },
      {
        title: 'Pemberhentian ASN',
        moduleKey: 'SIPENSIUN',
        children: [
          {
            title: 'Atas Permintaan Sendiri',
            path: '/sipensiun?jenis=APS',
            moduleKey: 'SIPENSIUN',
          },
          {
            title: 'Tidak Cakap Jasmani/Rohani',
            path: '/sipensiun?jenis=TIDAK_CAKAP',
            moduleKey: 'SIPENSIUN',
          },
          {
            title: 'Meninggal/Tewas/Hilang',
            path: '/sipensiun?jenis=MENINGGAL_TEWAS_HILANG',
            moduleKey: 'SIPENSIUN',
          },
          {
            title: 'Disiplin/Hukum',
            path: '/sipensiun?jenis=DISIPLIN_HUKUM',
            moduleKey: 'SIPENSIUN',
          },
          {
            title: 'Pemberhentian Sementara',
            path: '/sipensiun?jenis=SEMENTARA',
            moduleKey: 'SIPENSIUN',
          },
          {
            title: 'Pengaktifan Kembali',
            path: '/sipensiun?jenis=AKTIF_KEMBALI',
            moduleKey: 'SIPENSIUN',
          },
          {
            title: 'Perampingan Organisasi',
            path: '/sipensiun?jenis=PERAMPINGAN',
            moduleKey: 'SIPENSIUN',
          },
        ],
      },
      {
        title: 'Monitoring Status',
        path: '/sipensiun?view=monitoring',
        moduleKey: 'SIPENSIUN',
        requiredPermission: 'monitor',
      },
      {
        title: 'Penyerahan Keputusan',
        path: '/sipensiun?view=decision-delivery',
        moduleKey: 'SIPENSIUN',
        requiredPermission: 'input',
      },
      {
        title: 'Update Data Setelah SK',
        path: '/sipensiun?view=data-update',
        moduleKey: 'SIPENSIUN',
        requiredPermission: 'input',
      },
      {
        title: 'Laporan',
        path: '/sipensiun?view=reports',
        moduleKey: 'SIPENSIUN',
        requiredPermission: 'report',
      },
    ],
  },
  { heading: 'Control' },
  {
    title: 'Kalender Kerja',
    icon: CalendarDays,
    path: '/working-calendar',
    moduleKey: 'WORKING_CALENDAR',
  },
  {
    title: 'SIARSIP',
    icon: Archive,
    path: '/siarsip',
    moduleKey: 'SIARSIP',
  },
  {
    title: 'SIANALITIK',
    icon: BarChart3,
    path: '/sianalitik',
    moduleKey: 'SIANALITIK',
  },
  {
    title: 'Referensi SOP',
    icon: FileText,
    moduleKey: 'DMS',
    children: [
      {
        title: 'SOP Tahap 1 - Manajemen Bidang',
        path: '/dms/documents?category=DOKUMEN_KEBIJAKAN&subCategory=SOP_TAHAP_1',
        moduleKey: 'DMS',
      },
      {
        title: 'SOP Tahap 2 - Layanan Kepegawaian',
        path: '/dms/documents?category=DOKUMEN_KEBIJAKAN&subCategory=SOP_TAHAP_2',
        moduleKey: 'DMS',
      },
      {
        title: 'SOP Tahap 3 - Fungsi PPIK',
        path: '/dms/documents?category=DOKUMEN_KEBIJAKAN&subCategory=SOP_TAHAP_3',
        moduleKey: 'DMS',
      },
      {
        title: 'SOP Pensiun & Pemberhentian',
        path: '/dms/documents?category=DOKUMEN_KEBIJAKAN&subCategory=SOP_PENSIUN_PEMBERHENTIAN',
        moduleKey: 'DMS',
      },
      {
        title: 'Matriks SOP + Form + DMS',
        path: '/dms/documents?category=DOKUMEN_KEBIJAKAN&subCategory=SOP_MATRIKS',
        moduleKey: 'DMS',
      },
    ],
  },
  {
    title: 'RBAC',
    icon: ShieldCheck,
    path: '/admin/rbac',
    moduleKey: 'ADMIN',
    requiredPermission: 'admin',
    allowedRoles: ADMIN_ROLES,
  },
  {
    title: 'Pengguna',
    icon: Users,
    path: '/admin/users',
    moduleKey: 'ADMIN',
    requiredPermission: 'admin',
    allowedRoles: ADMIN_ROLES,
  },
  {
    title: 'Pengaturan',
    icon: Settings,
    path: '/admin/settings',
    moduleKey: 'ADMIN',
    requiredPermission: 'admin',
    allowedRoles: ADMIN_ROLES,
  },
];

export const MENU_MEGA: MenuConfig = MENU_SIDEBAR.filter((item) => !item.heading);
export const MENU_MEGA_MOBILE: MenuConfig = MENU_MEGA;
